### ISSUE TITLE
warning.js:45 Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See FormDemo

### ISSUE THREAD

**Issue by lee-my** [just-me-cy/antd-redux#1]
warning.js:45 Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See FormDemo

运行demo完全没问题 感谢分享~
浏览器报这个错不知道是什么原因..

**Comment by just-me-cy** [comment]
这个不是错，是警告，已经修正。
